In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
sales = pd.read_csv("../data/retail_sales_ml_apl.csv")

sales.head()

,Transaction Date,Sales Type,Is Return,Reason of Return,Supplier,Product No,Product Description,Product Division,Product Category,Product Subcategory,Product Segment,Store,Sales Channel,Qty Sold,Sales Amount,Cogs,Number of Transactions
0,2025-09-01,Full Price,0,NaN,Vendor 0169,PROD-139867,PROD-100449 SEG-500065 Scholar Footwear Trailb...,Scholar Footwear,Scholar Footwear Trailblazer,Scholar Footwear Trailblazer Equilibrium,SEG-500065 Scholar Footwear Trailblazer Equili...,STR-1006,Channel Alpha,1.0,115.00,52.31,1
1,2025-09-07,Full Price,0,NaN,Vendor 0166,PROD-100449,PROD-100825 SEG-500112 Heritage Footwear Fligh...,Femme Footwear,Femme Footwear Flight Classic,Femme Footwear Flight Classic Varied,SEG-500112 Heritage Footwear Flight Classic Ze...,STR-1198,Channel Alpha,1.0,115.00,58.47,1
2,2025-08-06,Promo,0,NaN,Vendor 0169,PROD-153623,PROD-148813 SEG-511388 Scholar Footwear Trailb...,Scholar Footwear,Scholar Footwear Trailblazer,Scholar Footwear Trailblazer Equilibrium,SEG-511388 Scholar Footwear Trailblazer Equili...,STR-1157,Channel Alpha,1.0,79.99,43.76,1
3,2025-08-31,Full Price,0,NaN,Vendor 0246,PROD-140876,PROD-100419 SEG-500063 Scholar Footwear Boot C...,Scholar Footwear,Scholar Footwear Boot Collection,Scholar Footwear Boot Collection Woodland,SEG-500063 Scholar Footwear Boot Collection Wo...,STR-1234,Channel Alpha,1.0,110.00,50.60,1
4,2026-03-22,Full Price,0,NaN,Vendor 0169,PROD-166113,PROD-149345 SEG-511444 Femme Footwear Trailbla...,Femme Footwear,Femme Footwear Trailblazer,Femme Footwear Trailblazer Equilibrium,SEG-511444 Femme Footwear Trailblazer Equilibrium,STR-1157,Channel Alpha,1.0,160.00,77.95,1

In [3]:
inventory = pd.read_csv("../data/retail_inventory_ml_apl.csv")

inventory.head()

,Start Date,End Date,Stock Status,Supplier,Product No,Product Description,Product Division,Product Category,Product Subcategory,Product Segment,Store,Store Type,Sales Channel,Qty on hand,Stocks Selling Amount,Cost of Stocks,Stock Unit Selling Price,Stock Unit Cost Price
0,2025-08-07,2025-10-18,Full Price,Vendor 0255,PROD-159369,PROD-103395 SEG-500461 Scholar Footwear Canvas...,Scholar Footwear,Scholar Footwear Canvas Styles,Scholar Footwear Canvas Styles Drifter,SEG-500461 Scholar Footwear Canvas Styles Drifter,STR-1010,Retail Storefront,Channel Alpha,1,55.0,24.75,55.0,24.75
1,2026-02-15,2026-02-15,Full Price,Vendor 0010,PROD-180713,PROD-190644 SEG-520887 Femme Footwear Court Ca...,Femme Footwear,Femme Footwear Court Casual,Femme Footwear Court Casual Trident,SEG-520887 Femme Footwear Court Casual Trident,STR-1082,Retail Storefront,Channel Alpha,1,130.0,59.73,130.0,59.73
2,2026-01-08,2026-02-15,Full Price,Vendor 0166,PROD-169474,PROD-153439 SEG-512518 Femme Footwear Court Ca...,Femme Footwear,Femme Footwear Court Casual,Femme Footwear Court Casual Zephyr,SEG-512518 Femme Footwear Court Casual Zephyr,STR-1105,Retail Storefront,Channel Alpha,1,120.0,60.44,120.0,60.44
3,2025-12-23,2026-02-15,Full Price,Vendor 0106,PROD-170976,PROD-122029 SEG-504463 Junior Apparel Cozy Pul...,Junior Apparel,Junior Apparel Cozy Pullovers,Junior Apparel Cozy Pullovers Varied,SEG-504463 Junior Apparel Cozy Pullovers Varied,STR-1157,Retail Storefront,Channel Alpha,3,150.0,52.50,50.0,17.50
4,2026-02-10,9999-12-31,Full Price,Vendor 0134,PROD-183525,PROD-111954 SEG-502325 Scholar Footwear Modern...,Scholar Footwear,Scholar Footwear Modern Legend,Scholar Footwear Modern Legend Summit,SEG-502325 Scholar Footwear Modern Legend Summit,STR-1253,Retail Storefront,Channel Alpha,4,360.0,182.16,90.0,45.54

In [4]:
print("Sales shape:", sales.shape)
print("Inventory shape:", inventory.shape)

Sales shape: (125751, 17)
Inventory shape: (284755, 18)

In [5]:
sales.columns
inventory.columns
sales.info()
inventory.info()

<class 'pandas.DataFrame'>
RangeIndex: 125751 entries, 0 to 125750
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Transaction Date        125751 non-null  str
 1   Sales Type              125751 non-null  str
 2   Is Return               125751 non-null  int64
 3   Reason of Return        0 non-null       float64
 4   Supplier                125751 non-null  str
 5   Product No              125751 non-null  str
 6   Product Description     125751 non-null  str
 7   Product Division        125751 non-null  str
 8   Product Category        125751 non-null  str
 9   Product Subcategory     125751 non-null  str
 10  Product Segment         125751 non-null  str
 11  Store                   125751 non-null  str
 12  Sales Channel           125751 non-null  str
 13  Qty Sold                125751 non-null  float64
 14  Sales Amount            125751 non-null  float64
 15  Cogs                    125751 non-null  float64
 16  Number of Transactions  125751 non-null  int64
dtypes: float64(4), int64(2), str(11)
memory usage: 46.2 MB
<class 'pandas.DataFrame'>
RangeIndex: 284755 entries, 0 to 284754
Data columns (total 18 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Start Date                284755 non-null  str
 1   End Date                  284755 non-null  str
 2   Stock Status              284755 non-null  str
 3   Supplier                  284755 non-null  str
 4   Product No                284755 non-null  str
 5   Product Description       284755 non-null  str
 6   Product Division          284755 non-null  str
 7   Product Category          284755 non-null  str
 8   Product Subcategory       284755 non-null  str
 9   Product Segment           284755 non-null  str
 10  Store                     284755 non-null  str
 11  Store Type                284755 non-null  str
 12  Sales Channel             284755 non-null  str
 13  Qty on hand               284755 non-null  int64
 14  Stocks Selling Amount     284755 non-null  float64
 15  Cost of Stocks            284755 non-null  float64
 16  Stock Unit Selling Price  284755 non-null  float64
 17  Stock Unit Cost Price     284755 non-null  float64
dtypes: float64(4), int64(1), str(13)
memory usage: 114.2 MB

In [6]:
sales.isnull().sum()
inventory.isnull().sum()
sales.isnull().mean().mul(100).round(2)
inventory.isnull().mean().mul(100).round(2)
print("Sales duplicates:", sales.duplicated().sum())
print("Inventory duplicates:", inventory.duplicated().sum())

Sales duplicates: 0
Inventory duplicates: 0

In [7]:
sales.isnull().sum()
inventory.isnull().sum()

Start Date                  0
End Date                    0
Stock Status                0
Supplier                    0
Product No                  0
Product Description         0
Product Division            0
Product Category            0
Product Subcategory         0
Product Segment             0
Store                       0
Store Type                  0
Sales Channel               0
Qty on hand                 0
Stocks Selling Amount       0
Cost of Stocks              0
Stock Unit Selling Price    0
Stock Unit Cost Price       0
dtype: int64

In [8]:
sales["Transaction Date"].head()
sales["Transaction Date"].tail()
sales["Transaction Date"].unique()[:10]
inventory["Start Date"].head()
inventory["End Date"].tail()
inventory["End Date"].value_counts().head(10)

End Date
9999-12-31    22701
2026-03-09     4527
2026-01-05     3601
2026-01-04     3485
2026-01-06     3203
2025-12-23     2640
2026-01-07     2511
2026-01-03     2419
2025-08-12     2135
2025-12-22     1999
Name: count, dtype: int64

In [9]:
# Convert Sales transaction date
sales["Transaction Date"] = pd.to_datetime(
    sales["Transaction Date"],
    errors="coerce"
)

# Convert Inventory start date
inventory["Start Date"] = pd.to_datetime(
    inventory["Start Date"],
    errors="coerce"
)

# Replace open-ended inventory date
inventory["End Date"] = inventory["End Date"].replace(
    "9999-12-31",
    pd.NaT
)

# Convert remaining inventory end dates
inventory["End Date"] = pd.to_datetime(
    inventory["End Date"],
    errors="coerce"
)
print(sales["Transaction Date"].dtype)
print(inventory["Start Date"].dtype)
print(inventory["End Date"].dtype)
print("Open-ended inventory records:", inventory["End Date"].isna().sum())
print("Sales date range:")
print(sales["Transaction Date"].min(), "to", sales["Transaction Date"].max())

print("\nInventory start date range:")
print(inventory["Start Date"].min(), "to", inventory["Start Date"].max())

print("\nInventory end date range:")
print(inventory["End Date"].min(), "to", inventory["End Date"].max())

datetime64[us]
datetime64[us]
datetime64[us]
Open-ended inventory records: 22701
Sales date range:
2025-06-01 00:00:00 to 2026-04-24 00:00:00

Inventory start date range:
2025-06-01 00:00:00 to 2026-04-24 00:00:00

Inventory end date range:
2025-06-01 00:00:00 to 2026-04-23 00:00:00

In [10]:
sales.describe()
inventory.describe()

,Start Date,End Date,Qty on hand,Stocks Selling Amount,Cost of Stocks,Stock Unit Selling Price,Stock Unit Cost Price
count,284755,262054,284755.000000,284755.000000,284755.000000,284755.000000,284755.000000
mean,2025-10-27 03:15:02.253516,2025-11-15 07:10:13.110274,2.294629,224.392566,111.046256,95.313171,47.419488
min,2025-06-01 00:00:00,2025-06-01 00:00:00,-9.000000,-828.000000,-418.950000,0.000000,-16.940000
25%,2025-08-12 00:00:00,2025-09-01 00:00:00,1.000000,95.000000,46.430000,75.000000,37.950000
50%,2025-10-25 00:00:00,2025-11-17 00:00:00,2.000000,160.000000,80.960000,100.000000,50.050000
75%,2026-01-06 00:00:00,2026-01-21 00:00:00,3.000000,300.000000,149.170000,120.000000,60.720000
max,2026-04-24 00:00:00,2026-04-23 00:00:00,56.000000,5600.000000,2641.450000,250.000000,336.380000
std,NaN,NaN,2.007395,214.479811,105.785092,46.655771,23.776569

In [11]:
print("Negative Qty on hand:",
      (inventory["Qty on hand"] < 0).sum())

print("Zero Qty on hand:",
      (inventory["Qty on hand"] == 0).sum())

print("Negative Stocks Selling Amount:",
      (inventory["Stocks Selling Amount"] < 0).sum())

print("Negative Cost of Stocks:",
      (inventory["Cost of Stocks"] < 0).sum())

print("Zero Stock Unit Selling Price:",
      (inventory["Stock Unit Selling Price"] == 0).sum())

print("Negative Stock Unit Cost Price:",
      (inventory["Stock Unit Cost Price"] < 0).sum())

inventory[inventory["Qty on hand"] < 0].head(10)
inventory[inventory["Stock Unit Cost Price"] < 0].head(10)

Negative Qty on hand: 1380
Zero Qty on hand: 13869
Negative Stocks Selling Amount: 1380
Negative Cost of Stocks: 8022
Zero Stock Unit Selling Price: 13869
Negative Stock Unit Cost Price: 25

,Start Date,End Date,Stock Status,Supplier,Product No,Product Description,Product Division,Product Category,Product Subcategory,Product Segment,Store,Store Type,Sales Channel,Qty on hand,Stocks Selling Amount,Cost of Stocks,Stock Unit Selling Price,Stock Unit Cost Price
6736,2025-08-24,2026-01-05,Full Price,Vendor 0054,PROD-161864,PROD-101707 SEG-500224 Scholar Footwear Sandal...,Scholar Footwear,Scholar Footwear Sandals,Scholar Footwear Sandals Varied,SEG-500224 Scholar Footwear Sandals Varied,STR-1148,Retail Storefront,Channel Alpha,-1,-40.0,1.62,40.0,-1.62
31741,2025-10-17,2025-10-25,Full Price,Vendor 0054,PROD-161864,PROD-101707 SEG-500224 Scholar Footwear Sandal...,Scholar Footwear,Scholar Footwear Sandals,Scholar Footwear Sandals Varied,SEG-500224 Scholar Footwear Sandals Varied,STR-1149,Retail Storefront,Channel Alpha,-1,-40.0,0.32,40.0,-0.32
45892,2025-08-30,2025-10-02,Full Price,Vendor 0054,PROD-161865,PROD-101708 SEG-500224 Scholar Footwear Sandal...,Scholar Footwear,Scholar Footwear Sandals,Scholar Footwear Sandals Varied,SEG-500224 Scholar Footwear Sandals Varied,STR-1194,Retail Storefront,Channel Alpha,1,40.0,-12.28,40.0,-12.28
52840,2025-09-09,2025-09-09,Full Price,Vendor 0054,PROD-161863,PROD-101706 SEG-500224 Scholar Footwear Sandal...,Scholar Footwear,Scholar Footwear Sandals,Scholar Footwear Sandals Varied,SEG-500224 Scholar Footwear Sandals Varied,STR-1006,Retail Storefront,Channel Alpha,1,40.0,-5.22,40.0,-5.22
65891,2025-08-23,2025-08-23,Full Price,Vendor 0054,PROD-161865,PROD-101708 SEG-500224 Scholar Footwear Sandal...,Scholar Footwear,Scholar Footwear Sandals,Scholar Footwear Sandals Varied,SEG-500224 Scholar Footwear Sandals Varied,STR-1148,Retail Storefront,Channel Alpha,1,40.0,-2.10,40.0,-2.10
112738,2025-11-22,2025-12-10,Full Price,Vendor 0054,PROD-161864,PROD-101707 SEG-500224 Scholar Footwear Sandal...,Scholar Footwear,Scholar Footwear Sandals,Scholar Footwear Sandals Varied,SEG-500224 Scholar Footwear Sandals Varied,STR-1203,Retail Storefront,Channel Alpha,1,40.0,-0.73,40.0,-0.73
116865,2025-11-03,2025-11-07,Full Price,Vendor 0084,PROD-185773,PROD-129687 SEG-506454 Junior Apparel Crew Tee...,Junior Apparel,Junior Apparel Crew Tees,Junior Apparel Crew Tees Varied,SEG-506454 Junior Apparel Crew Tees Varied,STR-1198,Retail Storefront,Channel Alpha,1,20.0,-0.19,20.0,-0.19
135602,2025-12-26,2025-12-29,Full Price,Vendor 0169,PROD-166366,PROD-102544 SEG-500347 Scholar Footwear Trailb...,Scholar Footwear,Scholar Footwear Trailblazer,Scholar Footwear Trailblazer Equilibrium,SEG-500347 Scholar Footwear Trailblazer Equili...,STR-1229,Retail Storefront,Channel Alpha,1,115.0,-5.71,115.0,-5.71
142486,2025-08-24,2025-08-26,Full Price,Vendor 0054,PROD-161865,PROD-101708 SEG-500224 Scholar Footwear Sandal...,Scholar Footwear,Scholar Footwear Sandals,Scholar Footwear Sandals Varied,SEG-500224 Scholar Footwear Sandals Varied,STR-1010,Retail Storefront,Channel Alpha,1,40.0,-3.54,40.0,-3.54
165401,2025-12-12,2025-12-31,Full Price,Vendor 0169,PROD-156688,PROD-103978 SEG-500562 Scholar Footwear Trailb...,Scholar Footwear,Scholar Footwear Trailblazer,Scholar Footwear Trailblazer Equilibrium,SEG-500562 Scholar Footwear Trailblazer Equili...,STR-1194,Retail Storefront,Channel Alpha,1,110.0,-12.36,110.0,-12.36

In [12]:
sales.describe()

,Transaction Date,Is Return,Reason of Return,Qty Sold,Sales Amount,Cogs,Number of Transactions
count,125751,125751.00000,0.0,125751.000000,125751.000000,125751.000000,125751.000000
mean,2025-11-12 05:16:43.039339,0.05957,NaN,0.930370,83.356079,46.502621,1.042695
min,2025-06-01 00:00:00,0.00000,NaN,-3.000000,-380.000000,-192.280000,1.000000
25%,2025-08-24 00:00:00,0.00000,NaN,1.000000,50.000000,37.710000,1.000000
50%,2025-11-21 00:00:00,0.00000,NaN,1.000000,90.000000,50.050000,1.000000
75%,2026-01-29 00:00:00,0.00000,NaN,1.000000,115.000000,60.720000,1.000000
max,2026-04-24 00:00:00,1.00000,NaN,14.000000,2660.000000,1345.960000,14.000000
std,NaN,0.23669,NaN,0.586897,83.658776,43.597511,0.305832

In [13]:
print("Total return records:")
print((sales["Is Return"] == 1).sum())

print("\nNegative quantity records:")
print((sales["Qty Sold"] < 0).sum())

print("\nNegative sales amount records:")
print((sales["Sales Amount"] < 0).sum())

print("\nNegative COGS records:")
print((sales["Cogs"] < 0).sum())

sales[sales["Is Return"] == 1][
    ["Is Return", "Qty Sold", "Sales Amount", "Cogs", "Number of Transactions"]
].head(20)

Total return records:
7491

Negative quantity records:
7491

Negative sales amount records:
7491

Negative COGS records:
7491

     Is Return  Qty Sold  Sales Amount   Cogs  Number of Transactions
39           1      -1.0       -165.00 -83.49                       1
47           1      -1.0        -69.99 -50.05                       1
68           1      -1.0        -60.00 -23.40                       1
115          1      -1.0        -63.00 -38.67                       1
151          1      -1.0       -120.00 -60.06                       1
153          1      -1.0       -110.00 -50.05                       1
162          1      -1.0        -90.00 -45.51                       1
168          1      -1.0       -112.00 -67.99                       1
190          1      -1.0       -110.00 -55.66                       1
200          1      -1.0        -81.00 -45.54                       1
206          1      -1.0        -75.00 -58.75                       1
229          1      -1.0        -85.00 -50.66                       1
249          1      -1.0       -160.00 -80.78                       1
251          1      -1.0       -185.00 -93.61                       1
255          1      -1.0       -125.00 -58.75                       1
269          1      -1.0        -89.99 -75.08                       1
272          1      -1.0        -59.99 -55.00                       1
317          1      -1.0       -110.00 -54.76                       1
327          1      -1.0        -29.99 -15.75                       1
346          1      -1.0        -69.99 -40.95                       1

In [14]:
inventory[inventory["Qty on hand"] < 0][
    [
        "Qty on hand",
        "Stocks Selling Amount",
        "Cost of Stocks",
        "Stock Unit Selling Price",
        "Stock Unit Cost Price"
    ]
].head(20)

inventory[inventory["Stock Unit Cost Price"] < 0][
    [
        "Qty on hand",
        "Stocks Selling Amount",
        "Cost of Stocks",
        "Stock Unit Selling Price",
        "Stock Unit Cost Price"
    ]
].head(20)

inventory[inventory["Stock Unit Selling Price"] == 0][
    [
        "Qty on hand",
        "Stocks Selling Amount",
        "Cost of Stocks",
        "Stock Unit Selling Price",
        "Stock Unit Cost Price"
    ]
].head(20)

,Qty on hand,Stocks Selling Amount,Cost of Stocks,Stock Unit Selling Price,Stock Unit Cost Price
5,0,0.0,-6.80,0.0,0.0
12,0,0.0,5.46,0.0,0.0
13,0,0.0,-0.15,0.0,0.0
14,0,0.0,-1.63,0.0,0.0
43,0,0.0,-0.01,0.0,0.0
44,0,0.0,-0.01,0.0,0.0
69,0,0.0,-0.06,0.0,0.0
143,0,0.0,-0.03,0.0,0.0
145,0,0.0,0.11,0.0,0.0
148,0,0.0,0.17,0.0,0.0
207,0,0.0,-1.40,0.0,0.0
236,0,0.0,3.74,0.0,0.0
239,0,0.0,-0.05,0.0,0.0
241,0,0.0,0.48,0.0,0.0
277,0,0.0,1.43,0.0,0.0
302,0,0.0,-0.01,0.0,0.0
416,0,0.0,-0.01,0.0,0.0
417,0,0.0,-0.01,0.0,0.0
430,0,0.0,-0.14,0.0,0.0
433,0,0.0,-0.70,0.0,0.0

In [15]:
inventory[inventory["Qty on hand"] < 0][
    [
        "Qty on hand",
        "Stocks Selling Amount",
        "Cost of Stocks",
        "Stock Unit Selling Price",
        "Stock Unit Cost Price"
    ]
].describe()

inventory[inventory["Cost of Stocks"] < 0][
    [
        "Qty on hand",
        "Stocks Selling Amount",
        "Cost of Stocks",
        "Stock Unit Selling Price",
        "Stock Unit Cost Price"
    ]
].describe()

inventory[inventory["Stock Unit Cost Price"] < 0][
    [
        "Qty on hand",
        "Stocks Selling Amount",
        "Cost of Stocks",
        "Stock Unit Selling Price",
        "Stock Unit Cost Price"
    ]
]

,Qty on hand,Stocks Selling Amount,Cost of Stocks,Stock Unit Selling Price,Stock Unit Cost Price
6736,-1,-40.00,1.62,40.00,-1.62
31741,-1,-40.00,0.32,40.00,-0.32
45892,1,40.00,-12.28,40.00,-12.28
52840,1,40.00,-5.22,40.00,-5.22
65891,1,40.00,-2.10,40.00,-2.10
112738,1,40.00,-0.73,40.00,-0.73
116865,1,20.00,-0.19,20.00,-0.19
135602,1,115.00,-5.71,115.00,-5.71
142486,1,40.00,-3.54,40.00,-3.54
165401,1,110.00,-12.36,110.00,-12.36
167485,1,150.00,-16.52,150.00,-16.52
174082,1,150.00,-9.83,150.00,-9.83
183457,1,40.00,-4.30,40.00,-4.30
187022,1,9.99,-1.20,9.99,-1.20
191099,1,40.00,-5.22,40.00,-5.22
192440,1,150.00,-16.94,150.00,-16.94
193081,1,115.00,-2.10,115.00,-2.10
211565,1,40.00,-0.31,40.00,-0.31
211885,-1,-20.00,13.09,20.00,-13.09
223848,1,40.00,-5.22,40.00,-5.22
231603,1,150.00,-9.83,150.00,-9.83
239693,-1,-9.99,13.09,9.99,-13.09
242538,1,150.00,-16.09,150.00,-16.09
244276,1,40.00,-0.56,40.00,-0.56
281996,1,20.00,-0.19,20.00,-0.19

In [16]:

#Check Sales Categories
categorical_sales = [
    "Sales Type",
    "Supplier",
    "Product Division",
    "Product Category",
    "Product Subcategory",
    "Product Segment",
    "Store",
    "Sales Channel"
]

for col in categorical_sales:
    print(f"\n--- {col} ---")
    print("Unique values:", sales[col].nunique())
    print(sales[col].unique()[:10])

#Check Inventory Categories
categorical_inventory = [
    "Stock Status",
    "Supplier",
    "Product Division",
    "Product Category",
    "Product Subcategory",
    "Product Segment",
    "Store",
    "Store Type",
    "Sales Channel"
]

for col in categorical_inventory:
    print(f"\n--- {col} ---")
    print("Unique values:", inventory[col].nunique())
    print(inventory[col].unique()[:10])

--- Sales Type ---
Unique values: 5
<ArrowStringArray>
['Full Price', 'Promo', 'Markdown Tier 1', 'Clearance', 'Markdown Tier 2']
Length: 5, dtype: str

--- Supplier ---
Unique values: 30
<ArrowStringArray>
['Vendor 0169', 'Vendor 0166', 'Vendor 0246', 'Vendor 0010', 'Vendor 0134',
 'Vendor 0064', 'Vendor 0106', 'Vendor 0258', 'Vendor 0054', 'Vendor 0008']
Length: 10, dtype: str

--- Product Division ---
Unique values: 3
<ArrowStringArray>
['Scholar Footwear', 'Femme Footwear', 'Junior Apparel']
Length: 3, dtype: str

--- Product Category ---
Unique values: 27
<ArrowStringArray>
[    'Scholar Footwear Trailblazer',    'Femme Footwear Flight Classic',
 'Scholar Footwear Boot Collection',       'Femme Footwear Trailblazer',
    'Scholar Footwear Court Casual',   'Scholar Footwear Modern Legend',
     'Junior Apparel Cozy Trousers',        'Junior Apparel Crop Pants',
    'Scholar Footwear Retro Legend',  'Scholar Footwear Flight Classic']
Length: 10, dtype: str

--- Product Subcategory ---
Unique values: 51
<ArrowStringArray>
[  'Scholar Footwear Trailblazer Equilibrium',
       'Femme Footwear Flight Classic Varied',
  'Scholar Footwear Boot Collection Woodland',
     'Femme Footwear Trailblazer Equilibrium',
      'Scholar Footwear Court Casual Trident',
      'Scholar Footwear Modern Legend Summit',
        'Junior Apparel Cozy Trousers Varied',
          'Femme Footwear Trailblazer Zephyr',
 'Scholar Footwear Boot Collection Plushfoot',
           'Junior Apparel Crop Pants Varied']
Length: 10, dtype: str

--- Product Segment ---
Unique values: 600
<ArrowStringArray>
[ 'SEG-500065 Scholar Footwear Trailblazer Equilibrium',
   'SEG-500112 Heritage Footwear Flight Classic Zephyr',
  'SEG-511388 Scholar Footwear Trailblazer Equilibrium',
 'SEG-500063 Scholar Footwear Boot Collection Woodland',
    'SEG-511444 Femme Footwear Trailblazer Equilibrium',
  'SEG-500349 Scholar Footwear Trailblazer Equilibrium',
     'SEG-500427 Scholar Footwear Court Casual Trident',
     'SEG-502364 Scholar Footwear Modern Legend Summit',
       'SEG-504485 Junior Apparel Cozy Trousers Varied',
         'SEG-520264 Femme Footwear Trailblazer Zephyr']
Length: 10, dtype: str

--- Store ---
Unique values: 40
<ArrowStringArray>
['STR-1006', 'STR-1198', 'STR-1157', 'STR-1234', 'STR-1075', 'STR-1338',
 'STR-1253', 'STR-1148', 'STR-1044', 'STR-1194']
Length: 10, dtype: str

--- Sales Channel ---
Unique values: 1
<ArrowStringArray>
['Channel Alpha']
Length: 1, dtype: str

--- Stock Status ---
Unique values: 5
<ArrowStringArray>
['Full Price', 'Markdown Tier 1', 'Markdown Tier 2', 'Clearance', 'Promo']
Length: 5, dtype: str

--- Supplier ---
Unique values: 30
<ArrowStringArray>
['Vendor 0255', 'Vendor 0010', 'Vendor 0166', 'Vendor 0106', 'Vendor 0134',
 'Vendor 0054', 'Vendor 0169', 'Vendor 0037', 'Vendor 0198', 'Vendor 0246']
Length: 10, dtype: str

--- Product Division ---
Unique values: 3
<ArrowStringArray>
['Scholar Footwear', 'Femme Footwear', 'Junior Apparel']
Length: 3, dtype: str

--- Product Category ---
Unique values: 27
<ArrowStringArray>
[ 'Scholar Footwear Canvas Styles',     'Femme Footwear Court Casual',
   'Junior Apparel Cozy Pullovers',  'Scholar Footwear Modern Legend',
 'Scholar Footwear Flight Classic',   'Scholar Footwear Court Casual',
        'Scholar Footwear Sandals',    'Junior Apparel Cozy Trousers',
    'Scholar Footwear Trailblazer',         'Junior Apparel Trousers']
Length: 10, dtype: str

--- Product Subcategory ---
Unique values: 51
<ArrowStringArray>
[  'Scholar Footwear Canvas Styles Drifter',
      'Femme Footwear Court Casual Trident',
       'Femme Footwear Court Casual Zephyr',
     'Junior Apparel Cozy Pullovers Varied',
    'Scholar Footwear Modern Legend Summit',
   'Scholar Footwear Flight Classic Zephyr',
    'Scholar Footwear Court Casual Trident',
          'Scholar Footwear Sandals Varied',
      'Junior Apparel Cozy Trousers Varied',
 'Scholar Footwear Trailblazer Equilibrium']
Length: 10, dtype: str

--- Product Segment ---
Unique values: 600
<ArrowStringArray>
['SEG-500461 Scholar Footwear Canvas Styles Drifter',
    'SEG-520887 Femme Footwear Court Casual Trident',
     'SEG-512518 Femme Footwear Court Casual Zephyr',
   'SEG-504463 Junior Apparel Cozy Pullovers Varied',
  'SEG-502325 Scholar Footwear Modern Legend Summit',
 'SEG-500125 Toddler Footwear Flight Classic Zephyr',
  'SEG-500406 Scholar Footwear Court Casual Trident',
  'SEG-502575 Scholar Footwear Modern Legend Summit',
        'SEG-500224 Scholar Footwear Sandals Varied',
     'SEG-515310 Femme Footwear Court Casual Zephyr']
Length: 10, dtype: str

--- Store ---
Unique values: 40
<ArrowStringArray>
['STR-1010', 'STR-1082', 'STR-1105', 'STR-1157', 'STR-1253', 'STR-1163',
 'STR-1074', 'STR-1234', 'STR-1335', 'STR-1145']
Length: 10, dtype: str

--- Store Type ---
Unique values: 1
<ArrowStringArray>
['Retail Storefront']
Length: 1, dtype: str

--- Sales Channel ---
Unique values: 1
<ArrowStringArray>
['Channel Alpha']
Length: 1, dtype: str

In [17]:
#Products
sales_products = set(sales["Product No"].unique())
inventory_products = set(inventory["Product No"].unique())

print("Products in Sales:", len(sales_products))
print("Products in Inventory:", len(inventory_products))

print("Sales products missing from Inventory:",
      len(sales_products - inventory_products))

print("Inventory products missing from Sales:",
      len(inventory_products - sales_products))

#Stores
sales_stores = set(sales["Store"].unique())
inventory_stores = set(inventory["Store"].unique())

print("Stores in Sales:", len(sales_stores))
print("Stores in Inventory:", len(inventory_stores))

print("Sales stores missing from Inventory:",
      len(sales_stores - inventory_stores))

print("Inventory stores missing from Sales:",
      len(inventory_stores - sales_stores))

Products in Sales: 2326
Products in Inventory: 2326
Sales products missing from Inventory: 0
Inventory products missing from Sales: 0
Stores in Sales: 40
Stores in Inventory: 40
Sales stores missing from Inventory: 0
Inventory stores missing from Sales: 0

In [18]:
sales_clean = sales.copy()
inventory_clean = inventory.copy()

In [19]:
sales_clean = sales_clean.drop(columns=["Reason of Return"])
sales_clean.shape

(125751, 16)

In [20]:
sales_text_columns = sales_clean.select_dtypes(include="string").columns

for col in sales_text_columns:
    sales_clean[col] = sales_clean[col].str.strip()

inventory_text_columns = inventory_clean.select_dtypes(include="string").columns

for col in inventory_text_columns:
    inventory_clean[col] = inventory_clean[col].str.strip()

In [21]:
#Gross Sales
sales_clean["Gross Sales"] = sales_clean["Sales Amount"].clip(lower=0)

#Retuen Amount
sales_clean["Return Amount"] = sales_clean["Sales Amount"].clip(upper=0).abs()

#Net Sales
sales_clean["Net Sales"] = sales_clean["Sales Amount"]

#Profit
sales_clean["Profit"] = (
    sales_clean["Sales Amount"] - sales_clean["Cogs"]
)

#Profit Margin 
sales_clean["Profit Margin"] = np.where(
    sales_clean["Net Sales"] != 0,
    sales_clean["Profit"] / sales_clean["Net Sales"],
    0
)

#Month
sales_clean["Month"] = sales_clean["Transaction Date"].dt.to_period("M").astype(str)

#Year 
sales_clean["Year"] = sales_clean["Transaction Date"].dt.year

#Month Name
sales_clean["Month Name"] = sales_clean["Transaction Date"].dt.strftime("%B")

#Inventory Value
inventory_clean["Inventory Value"] = inventory_clean["Stocks Selling Amount"]

#Inventory Cost
inventory_clean["Inventory Cost"] = inventory_clean["Cost of Stocks"]

#Stock availability flag
inventory_clean["Stock Available"] = np.where(
    inventory_clean["Qty on hand"] > 0,
    "In Stock",
    "Out of Stock"
)

#Negative inventory flag
inventory_clean["Negative Stock Flag"] = np.where(
    inventory_clean["Qty on hand"] < 0,
    "Negative Stock",
    "Normal"
)

In [22]:
sales_clean[
    [
        "Sales Amount",
        "Cogs",
        "Gross Sales",
        "Return Amount",
        "Net Sales",
        "Profit",
        "Profit Margin"
    ]
].head(10)

inventory_clean[
    [
        "Qty on hand",
        "Inventory Value",
        "Inventory Cost",
        "Stock Available",
        "Negative Stock Flag"
    ]
].head(10)

sales_clean.to_csv(
    "../data/retail_sales_clean.csv",
    index=False
)

inventory_clean.to_csv(
    "../data/retail_inventory_clean.csv",
    index=False
)

In [23]:
total_gross_sales = sales_clean["Gross Sales"].sum()
total_returns = sales_clean["Return Amount"].sum()
net_sales = sales_clean["Net Sales"].sum()
total_cogs = sales_clean["Cogs"].sum()
total_profit = sales_clean["Profit"].sum()
total_units = sales_clean["Qty Sold"].sum()
total_transactions = sales_clean["Number of Transactions"].sum()

profit_margin = total_profit / net_sales
return_rate = total_returns / total_gross_sales

print("Total Gross Sales:", round(total_gross_sales, 2))
print("Total Returns:", round(total_returns, 2))
print("Net Sales:", round(net_sales, 2))
print("Total COGS:", round(total_cogs, 2))
print("Total Profit:", round(total_profit, 2))
print("Total Units Sold:", round(total_units, 2))
print("Total Transactions:", total_transactions)
print("Profit Margin:", round(profit_margin * 100, 2), "%")
print("Return Rate:", round(return_rate * 100, 2), "%")

Total Gross Sales: 11215681.26
Total Returns: 733571.01
Net Sales: 10482110.25
Total COGS: 5847751.1
Total Profit: 4634359.15
Total Units Sold: 116995.0
Total Transactions: 131120
Profit Margin: 44.21 %
Return Rate: 6.54 %

In [24]:
#Store Performance
store_performance = (
    sales_clean
    .groupby("Store")
    .agg(
        Net_Sales=("Net Sales", "sum"),
        Profit=("Profit", "sum"),
        Units_Sold=("Qty Sold", "sum"),
        Transactions=("Number of Transactions", "sum")
    )
    .reset_index()
)

store_performance["Profit_Margin"] = (
    store_performance["Profit"] /
    store_performance["Net_Sales"]
)

store_performance.sort_values(
    "Net_Sales",
    ascending=False
).head(10)

store_performance.sort_values(
    "Profit",
    ascending=False
).head(10)

       Store  Net_Sales       Profit  Units_Sold  Transactions  Profit_Margin
0   STR-1006  485561.44  225775.1401      5619.0          6165       0.464977
25  STR-1229  399696.48  177312.8700      3817.0          4228       0.443619
7   STR-1080  371277.03  171695.0900      3461.0          3935       0.462445
20  STR-1194  346391.53  154103.8700      4056.0          4512       0.444883
1   STR-1010  343436.84  151108.6700      4554.0          5039       0.439990
24  STR-1222  329188.10  150422.7700      3200.0          3590       0.456951
4   STR-1044  328466.36  149385.2700      3945.0          4353       0.454796
27  STR-1235  335338.71  149101.6000      3082.0          3445       0.444630
6   STR-1075  327931.80  147722.3900      3695.0          4101       0.450467
16  STR-1148  332396.05  147233.9800      4392.0          4895       0.442947

In [25]:
#Product Performance
product_performance = (
    sales_clean
    .groupby(["Product No", "Product Description"])
    .agg(
        Net_Sales=("Net Sales", "sum"),
        Profit=("Profit", "sum"),
        Units_Sold=("Qty Sold", "sum"),
        Transactions=("Number of Transactions", "sum")
    )
    .reset_index()
)

product_performance["Profit_Margin"] = (
    product_performance["Profit"] /
    product_performance["Net_Sales"]
)

product_performance.sort_values(
    "Net_Sales",
    ascending=False
).head(10)

product_performance.sort_values(
    "Profit",
    ascending=False
).head(10)

product_performance.sort_values(
    "Profit",
    ascending=False
).head(10)

,Product No,Product Description,Net_Sales,Profit,Units_Sold,Transactions,Profit_Margin
276,PROD-140871,PROD-100439 SEG-500064 Scholar Footwear Boot C...,104027.50,57439.66,915.0,1036,0.552158
39,PROD-100805,PROD-102578 SEG-500351 Scholar Footwear Flight...,102481.99,49202.94,1170.0,1266,0.480113
38,PROD-100804,PROD-102576 SEG-500351 Scholar Footwear Flight...,72822.50,34853.66,834.0,911,0.478611
37,PROD-100803,PROD-102577 SEG-500351 Scholar Footwear Flight...,71496.48,34345.32,816.0,887,0.480378
275,PROD-140870,PROD-100438 SEG-500064 Scholar Footwear Boot C...,61705.00,33924.64,546.0,609,0.549788
274,PROD-140869,PROD-100437 SEG-500064 Scholar Footwear Boot C...,55251.90,30686.63,483.0,540,0.555395
1806,PROD-175338,PROD-113366 SEG-502458 Heritage Footwear Retro...,60040.00,29659.76,316.0,316,0.494000
36,PROD-100802,PROD-102574 SEG-500351 Scholar Footwear Flight...,56361.50,27220.29,640.0,697,0.482959
1804,PROD-175334,PROD-113357 SEG-502458 Heritage Footwear Retro...,51110.00,25248.34,269.0,278,0.494000
465,PROD-152143,PROD-162923 SEG-514991 Heritage Footwear Retro...,45672.00,22611.54,288.0,308,0.495085

In [27]:
#Category Performance
category_performance = (
    sales_clean
    .groupby("Product Category")
    .agg(
        Net_Sales=("Net Sales", "sum"),
        Profit=("Profit", "sum"),
        Units_Sold=("Qty Sold", "sum"),
        Transactions=("Number of Transactions", "sum")
    )
    .reset_index()
)

category_performance["Profit_Margin"] = (
    category_performance["Profit"] /
    category_performance["Net_Sales"]
)

category_performance = category_performance.sort_values(
    "Net_Sales",
    ascending=False
)

category_performance
category_performance.head(10)
category_performance.sort_values(
    "Profit",
    ascending=False
).head(10)

,Product Category,Net_Sales,Profit,Units_Sold,Transactions,Profit_Margin
25,Scholar Footwear Trailblazer,1909759.99,927715.3700,20584.0,23117,0.485776
23,Scholar Footwear Retro Legend,1920958.56,905344.3400,12569.0,13801,0.471298
5,Femme Footwear Trailblazer,1238790.65,436689.0400,12325.0,14536,0.352512
22,Scholar Footwear Modern Legend,1062646.92,405024.2800,10731.0,12207,0.381147
17,Scholar Footwear Boot Collection,660152.85,358274.6600,6049.0,6875,0.542715
20,Scholar Footwear Flight Classic,767298.33,354519.3300,8926.0,9846,0.462036
19,Scholar Footwear Court Casual,702385.90,281848.1800,9530.0,10762,0.401273
1,Femme Footwear Court Casual,647820.37,240117.8001,7279.0,8368,0.370655
0,Femme Footwear Boot Collection,304630.62,154503.4900,2321.0,2949,0.507183
2,Femme Footwear Flight Classic,303495.26,140888.6700,2728.0,3068,0.464220

In [26]:

#Monthly Sales Trend
monthly_sales = (
    sales_clean
    .groupby("Month")
    .agg(
        Net_Sales=("Net Sales", "sum"),
        Profit=("Profit", "sum"),
        Units_Sold=("Qty Sold", "sum"),
        Transactions=("Number of Transactions", "sum")
    )
    .reset_index()
)

monthly_sales

      Month   Net_Sales       Profit  Units_Sold  Transactions
0   2025-06   706683.44  332964.5100      7712.0          8593
1   2025-07   855571.55  392780.1000      9545.0         10567
2   2025-08  1535117.21  703591.1100     17561.0         19136
3   2025-09   860457.23  372588.2700      9654.0         10916
4   2025-10   821266.08  351700.4900      9226.0         10173
5   2025-11   871946.34  388296.6200      9527.0         10571
6   2025-12  1785534.95  796351.9000     18717.0         21358
7   2026-01   565272.83  228670.4201      6609.0          8097
8   2026-02  1038967.86  476303.6300     10222.0         11495
9   2026-03   934194.48  378314.5900     11882.0         13198
10  2026-04   507098.28  212797.5100      6340.0          7016

In [28]:
print("Overall Net Sales:", sales_clean["Net Sales"].sum())

print(
    "Category Net Sales:",
    category_performance["Net_Sales"].sum()
)
print(
    sales_clean["Product Category"].isna().sum()
)

print(
    sales_clean["Product Category"].nunique()
)
print(
    category_performance["Net_Sales"].sum() /
    sales_clean["Net Sales"].sum()
)

Overall Net Sales: 10482110.25
Category Net Sales: 10482110.25
0
27
1.0

In [29]:
#Inventory Analysis
#Overall Inventory KPIs
total_inventory_units = inventory_clean["Qty on hand"].sum()
total_inventory_value = inventory_clean["Inventory Value"].sum()
total_inventory_cost = inventory_clean["Inventory Cost"].sum()

out_of_stock = (
    inventory_clean["Qty on hand"] == 0
).sum()

negative_stock = (
    inventory_clean["Qty on hand"] < 0
).sum()

in_stock = (
    inventory_clean["Qty on hand"] > 0
).sum()

print("Total Inventory Units:", total_inventory_units)
print("Total Inventory Value:", round(total_inventory_value, 2))
print("Total Inventory Cost:", round(total_inventory_cost, 2))
print("In-Stock Records:", in_stock)
print("Out-of-Stock Records:", out_of_stock)
print("Negative Stock Records:", negative_stock)

Total Inventory Units: 653407
Total Inventory Value: 63896905.11
Total Inventory Cost: 31620976.61
In-Stock Records: 269506
Out-of-Stock Records: 13869
Negative Stock Records: 1380

In [30]:
#Stock availability percentage
total_records = len(inventory_clean)

print(
    "Out-of-Stock %:",
    round((out_of_stock / total_records) * 100, 2),
    "%"
)

print(
    "In-Stock %:",
    round((in_stock / total_records) * 100, 2),
    "%"
)

Out-of-Stock %: 4.87 %
In-Stock %: 94.64 %

In [31]:
#Inventory by store
inventory_by_store = (
    inventory_clean
    .groupby("Store")
    .agg(
        Inventory_Units=("Qty on hand", "sum"),
        Inventory_Value=("Inventory Value", "sum"),
        Inventory_Cost=("Inventory Cost", "sum")
    )
    .reset_index()
    .sort_values("Inventory_Value", ascending=False)
)

inventory_by_store.head(10)

       Store  Inventory_Units  Inventory_Value  Inventory_Cost
0   STR-1006            28771       2729701.91      1319815.28
25  STR-1229            19274       2199976.69      1087974.83
1   STR-1010            24374       2084988.09      1033462.30
4   STR-1044            21895       2044730.31       998888.99
21  STR-1198            31392       2031560.92      1045904.99
24  STR-1222            18730       1999878.11       981585.27
10  STR-1094            20778       1981819.72       982142.55
13  STR-1109            21385       1944595.30       959684.06
16  STR-1148            21156       1890075.20       932555.82
7   STR-1080            16466       1856854.20       916544.92

In [32]:
#Inventory by product
inventory_by_product = (
    inventory_clean
    .groupby(["Product No", "Product Description"])
    .agg(
        Inventory_Units=("Qty on hand", "sum"),
        Inventory_Value=("Inventory Value", "sum"),
        Inventory_Cost=("Inventory Cost", "sum")
    )
    .reset_index()
    .sort_values("Inventory_Value", ascending=False)
)

inventory_by_product.head(10)

,Product No,Product Description,Inventory_Units,Inventory_Value,Inventory_Cost
39,PROD-100805,PROD-102578 SEG-500351 Scholar Footwear Flight...,15989,1439010.0,728358.13
276,PROD-140871,PROD-100439 SEG-500064 Scholar Footwear Boot C...,9676,1145740.0,493283.92
37,PROD-100803,PROD-102577 SEG-500351 Scholar Footwear Flight...,11128,1001520.0,505700.22
38,PROD-100804,PROD-102576 SEG-500351 Scholar Footwear Flight...,11091,998190.0,506093.78
21,PROD-100439,PROD-164668 SEG-515333 Scholar Footwear Court ...,10824,985774.0,498921.61
20,PROD-100438,PROD-164666 SEG-515333 Scholar Footwear Court ...,6568,598426.0,303067.25
284,PROD-140879,PROD-100422 SEG-500063 Scholar Footwear Boot C...,4629,549980.0,234232.00
47,PROD-100813,PROD-100959 SEG-500123 Scholar Footwear Flight...,6018,541620.0,274888.45
275,PROD-140870,PROD-100438 SEG-500064 Scholar Footwear Boot C...,4286,507120.0,218575.16
19,PROD-100437,PROD-164667 SEG-515333 Scholar Footwear Court ...,5558,506230.0,256356.39

In [33]:
out_of_stock_products = inventory_clean[
    inventory_clean["Qty on hand"] == 0
].groupby(
    ["Product No", "Product Description"]
).size().reset_index(name="Out_of_Stock_Records")

out_of_stock_products.sort_values(
    "Out_of_Stock_Records",
    ascending=False
).head(10)

,Product No,Product Description,Out_of_Stock_Records
631,PROD-166368,PROD-102546 SEG-500347 Scholar Footwear Trailb...,107
628,PROD-166365,PROD-102543 SEG-500347 Scholar Footwear Trailb...,98
630,PROD-166367,PROD-102545 SEG-500347 Scholar Footwear Trailb...,95
629,PROD-166366,PROD-102544 SEG-500347 Scholar Footwear Trailb...,90
627,PROD-166364,PROD-102542 SEG-500347 Scholar Footwear Trailb...,87
626,PROD-166363,PROD-102541 SEG-500347 Scholar Footwear Trailb...,86
625,PROD-166362,PROD-102540 SEG-500347 Scholar Footwear Trailb...,85
10,PROD-100359,PROD-164495 SEG-515310 Femme Footwear Court Ca...,84
81,PROD-121532,PROD-102948 SEG-500406 Scholar Footwear Court ...,82
14,PROD-100433,PROD-164663 SEG-515333 Scholar Footwear Court ...,79

In [34]:
#Inventory by category
inventory_by_category = (
    inventory_clean
    .groupby("Product Category")
    .agg(
        Inventory_Units=("Qty on hand", "sum"),
        Inventory_Value=("Inventory Value", "sum"),
        Inventory_Cost=("Inventory Cost", "sum")
    )
    .reset_index()
    .sort_values("Inventory_Value", ascending=False)
)

inventory_by_category

,Product Category,Inventory_Units,Inventory_Value,Inventory_Cost
25,Scholar Footwear Trailblazer,82519,8587645.22,3998935.53
20,Scholar Footwear Flight Classic,93128,8449155.80,4277997.67
23,Scholar Footwear Retro Legend,48268,7534237.76,3870161.03
5,Femme Footwear Trailblazer,53303,6927289.06,3615506.18
22,Scholar Footwear Modern Legend,51891,6004085.88,3194923.36
19,Scholar Footwear Court Casual,65997,5755741.41,2916101.12
17,Scholar Footwear Boot Collection,47890,5501169.61,2399016.04
1,Femme Footwear Court Casual,44647,5000013.58,2515196.17
0,Femme Footwear Boot Collection,17240,2340960.00,1090851.73
2,Femme Footwear Flight Classic,16309,1895484.60,960624.27
4,Femme Footwear Retro Legend,3881,831824.57,421459.85
6,Junior Apparel Cozy Pullovers,19955,790207.96,372614.55
7,Junior Apparel Cozy Trousers,18314,695293.78,317479.44
24,Scholar Footwear Sandals,12550,593936.25,243460.95
8,Junior Apparel Crew Tees,21521,578290.83,237693.25
21,Scholar Footwear Hardcourt,3146,575899.76,292241.18
26,Scholar Footwear Trainer,3841,381014.00,180869.56
15,Junior Apparel Printed Tees,20412,258076.01,134512.32
18,Scholar Footwear Canvas Styles,3711,212585.00,94965.82
11,Junior Apparel Gift Bundles,5820,204693.18,97075.63
3,Femme Footwear Modern Legend,1651,203159.10,104837.37
9,Junior Apparel Crop Pants,6673,196805.60,80738.47
16,Junior Apparel Trousers,5435,129930.28,74979.36
10,Junior Apparel Denim Classics,2647,94991.70,45902.50
14,Junior Apparel Outer Shells,651,63490.00,29205.40
13,Junior Apparel Miscellany,1058,51662.04,21447.80
12,Junior Apparel Light Shells,949,39262.13,32180.06

In [35]:
#Stock Status Analysis
stock_status = (
    inventory_clean["Stock Status"]
    .value_counts()
    .reset_index()
)

stock_status.columns = ["Stock Status", "Count"]

stock_status
inventory_clean["Stock Status"].unique()

<ArrowStringArray>
['Full Price', 'Markdown Tier 1', 'Markdown Tier 2', 'Clearance', 'Promo']
Length: 5, dtype: str

In [36]:
#Sales + Inventory
product_sales = (
    sales_clean
    .groupby(["Product No", "Product Description"])
    .agg(
        Net_Sales=("Net Sales", "sum"),
        Units_Sold=("Qty Sold", "sum"),
        Profit=("Profit", "sum")
    )
    .reset_index()
)

product_inventory = (
    inventory_clean
    .groupby(["Product No", "Product Description"])
    .agg(
        Inventory_Units=("Qty on hand", "sum"),
        Inventory_Value=("Inventory Value", "sum")
    )
    .reset_index()
)

product_sales_inventory = product_sales.merge(
    product_inventory,
    on=["Product No", "Product Description"],
    how="left"
)

product_sales_inventory.head()

,Product No,Product Description,Net_Sales,Units_Sold,Profit,Inventory_Units,Inventory_Value
0,PROD-100043,PROD-189472 SEG-520541 Femme Footwear Boot Col...,2432.0,16.0,1335.45,74,11840.0
1,PROD-100044,PROD-189473 SEG-520541 Femme Footwear Boot Col...,3792.0,24.0,2145.29,129,20640.0
2,PROD-100045,PROD-189474 SEG-520541 Femme Footwear Boot Col...,2104.0,14.0,1139.11,69,11040.0
3,PROD-100051,PROD-189481 SEG-520542 Femme Footwear Boot Col...,1600.0,10.0,896.39,38,6080.0
4,PROD-100052,PROD-189475 SEG-520542 Femme Footwear Boot Col...,1760.0,11.0,988.46,70,11200.0

In [37]:
product_sales_inventory["Inventory_Coverage"] = np.where(
    product_sales_inventory["Units_Sold"] > 0,
    product_sales_inventory["Inventory_Units"] /
    product_sales_inventory["Units_Sold"],
    np.nan
)

In [38]:
product_store_counts = (
    inventory_clean
    .groupby(["Product No", "Store"])
    .size()
    .reset_index(name="Record_Count")
)

product_store_counts["Record_Count"].describe()
product_store_counts["Record_Count"].value_counts().sort_index()

Record_Count
1      5360
2     15177
3     11339
4      7347
5      6324
      ...
68        2
70        2
71        1
76        1
86        1
Name: count, Length: 71, dtype: int64

In [39]:
#Find the latest inventory record
latest_inventory = (
    inventory_clean
    .sort_values("Start Date")
    .groupby(["Product No", "Store"], as_index=False)
    .tail(1)
)

print("Original inventory records:", len(inventory_clean))
print("Latest inventory records:", len(latest_inventory))

latest_inventory[
    [
        "Product No",
        "Store",
        "Start Date",
        "End Date",
        "Qty on hand",
        "Inventory Value",
        "Inventory Cost"
    ]
].head(10)

Original inventory records: 284755
Latest inventory records: 60968

,Product No,Store,Start Date,End Date,Qty on hand,Inventory Value,Inventory Cost
169943,PROD-159582,STR-1109,2025-06-01,2025-07-30,1,90.0,45.04
170540,PROD-124593,STR-1157,2025-06-01,2026-01-04,0,0.0,3.80
34041,PROD-158662,STR-1148,2025-06-01,2025-07-25,1,170.0,80.08
175798,PROD-158530,STR-1080,2025-06-01,2025-10-08,1,120.0,57.56
32486,PROD-125402,STR-1194,2025-06-01,2026-01-03,1,125.0,51.70
2680,PROD-171869,STR-1222,2025-06-01,2026-02-12,2,64.0,16.00
173702,PROD-158663,STR-1094,2025-06-01,2026-02-21,2,340.0,160.16
33252,PROD-160873,STR-1338,2025-06-01,2025-08-13,1,160.0,80.08
174230,PROD-158659,STR-1107,2025-06-01,2025-06-02,1,170.0,80.08
173701,PROD-158658,STR-1194,2025-06-01,2026-02-21,1,170.0,80.08

In [40]:
#Product-level current inventory
current_product_inventory = (
    latest_inventory
    .groupby(["Product No", "Product Description"])
    .agg(
        Current_Inventory_Units=("Qty on hand", "sum"),
        Current_Inventory_Value=("Inventory Value", "sum"),
        Current_Inventory_Cost=("Inventory Cost", "sum")
    )
    .reset_index()
)

current_product_inventory.sort_values(
    "Current_Inventory_Value",
    ascending=False
).head(10)

,Product No,Product Description,Current_Inventory_Units,Current_Inventory_Value,Current_Inventory_Cost
1806,PROD-175338,PROD-113366 SEG-502458 Heritage Footwear Retro...,287,54530.0,27592.18
1804,PROD-175334,PROD-113357 SEG-502458 Heritage Footwear Retro...,196,37240.0,18843.44
47,PROD-100813,PROD-100959 SEG-500123 Scholar Footwear Flight...,339,30510.0,15436.56
1976,PROD-178777,PROD-113925 SEG-502507 Heritage Footwear Retro...,171,28215.0,14276.79
45,PROD-100811,PROD-100957 SEG-500123 Scholar Footwear Flight...,304,27360.0,13843.95
46,PROD-100812,PROD-100955 SEG-500123 Scholar Footwear Flight...,282,25380.0,12842.78
1805,PROD-175335,PROD-113355 SEG-502458 Heritage Footwear Retro...,132,25080.0,12690.48
1803,PROD-175333,PROD-113350 SEG-502458 Heritage Footwear Retro...,113,21470.0,10863.82
32,PROD-100798,PROD-102571 SEG-500351 Scholar Footwear Flight...,224,20160.0,10202.44
1802,PROD-175332,PROD-113352 SEG-502458 Heritage Footwear Retro...,104,19760.0,9998.56

In [41]:
#Sales + Current Inventory
product_sales = (
    sales_clean
    .groupby(["Product No", "Product Description"])
    .agg(
        Net_Sales=("Net Sales", "sum"),
        Units_Sold=("Qty Sold", "sum"),
        Profit=("Profit", "sum")
    )
    .reset_index()
)

product_sales_inventory = product_sales.merge(
    current_product_inventory,
    on=["Product No", "Product Description"],
    how="left"
)
product_sales_inventory.head()

,Product No,Product Description,Net_Sales,Units_Sold,Profit,Current_Inventory_Units,Current_Inventory_Value,Current_Inventory_Cost
0,PROD-100043,PROD-189472 SEG-520541 Femme Footwear Boot Col...,2432.0,16.0,1335.45,30,4800.0,2043.36
1,PROD-100044,PROD-189473 SEG-520541 Femme Footwear Boot Col...,3792.0,24.0,2145.29,29,4640.0,1973.21
2,PROD-100045,PROD-189474 SEG-520541 Femme Footwear Boot Col...,2104.0,14.0,1139.11,22,3520.0,1514.45
3,PROD-100051,PROD-189481 SEG-520542 Femme Footwear Boot Col...,1600.0,10.0,896.39,11,1760.0,775.00
4,PROD-100052,PROD-189475 SEG-520542 Femme Footwear Boot Col...,1760.0,11.0,988.46,28,4480.0,1973.44

In [42]:
#Create stock-risk indicator
stockout_risk = product_sales_inventory[
    (product_sales_inventory["Units_Sold"] > 0) &
    (product_sales_inventory["Current_Inventory_Units"] <= 0)
].copy()

stockout_risk.sort_values(
    "Units_Sold",
    ascending=False
).head(20)

,Product No,Product Description,Net_Sales,Units_Sold,Profit,Current_Inventory_Units,Current_Inventory_Value,Current_Inventory_Cost
12,PROD-100360,PROD-164482 SEG-515310 Femme Footwear Court Ca...,4679.91,59.0,1187.68,0,0.00,2.70
148,PROD-123509,PROD-171497 SEG-516514 Junior Apparel Crop Pan...,822.43,34.0,274.46,-2,-110.02,-26.79
979,PROD-163861,PROD-180137 SEG-518154 Femme Footwear Trailbla...,1499.90,19.0,552.50,-1,-100.00,-50.28

In [43]:
product_sales_inventory["Inventory_to_Sales_Ratio"] = np.where(
    product_sales_inventory["Net_Sales"] > 0,
    product_sales_inventory["Current_Inventory_Value"] /
    product_sales_inventory["Net_Sales"],
    np.nan
)

product_sales_inventory.sort_values(
    "Inventory_to_Sales_Ratio",
    ascending=False
).head(20)

,Product No,Product Description,Net_Sales,Units_Sold,Profit,Current_Inventory_Units,Current_Inventory_Value,Current_Inventory_Cost,Inventory_to_Sales_Ratio
520,PROD-152708,PROD-166588 SEG-515644 Femme Footwear Trailbla...,1729.97,10.0,779.07,58,11499.99,5515.34,6.647508
1257,PROD-168499,PROD-187243 SEG-520058 Femme Footwear Boot Col...,1500.00,10.0,842.00,69,9660.00,4540.18,6.440000
522,PROD-152711,PROD-166591 SEG-515644 Femme Footwear Trailbla...,2198.88,16.0,677.43,68,13399.98,6466.19,6.094002
1037,PROD-165578,PROD-109666 SEG-502021 Femme Footwear Court Ca...,1544.44,16.0,661.24,78,9360.00,4305.60,6.060449
1749,PROD-173379,PROD-108108 SEG-501609 Junior Apparel Denim Cl...,315.43,10.0,120.43,40,1800.00,780.00,5.706496
1035,PROD-165576,PROD-109664 SEG-502021 Femme Footwear Court Ca...,1684.94,16.0,801.74,80,9600.00,4416.00,5.697532
1867,PROD-175940,PROD-153425 SEG-512517 Femme Footwear Court Ca...,1670.50,13.0,815.36,71,9230.00,4670.38,5.525292
2260,PROD-190416,PROD-137181 SEG-508412 Junior Apparel Crew Tee...,320.00,8.0,224.00,43,1720.00,516.00,5.375000
1982,PROD-178806,PROD-141517 SEG-509388 Scholar Footwear Hardco...,3135.75,18.0,1450.77,90,16650.00,8424.90,5.309735
1689,PROD-171014,PROD-122049 SEG-504468 Junior Apparel Cozy Tro...,406.90,11.0,175.90,36,2160.00,756.00,5.308430
1894,PROD-175997,PROD-166631 SEG-515650 Femme Footwear Trailbla...,1765.25,14.0,808.91,66,8910.00,4508.46,5.047444
1688,PROD-171013,PROD-122050 SEG-504468 Junior Apparel Cozy Tro...,429.93,10.0,219.93,36,2160.00,756.00,5.024074
403,PROD-149692,PROD-103117 SEG-500427 Scholar Footwear Court ...,3009.92,40.0,1518.96,189,15120.00,7048.65,5.023389
1036,PROD-165577,PROD-109665 SEG-502021 Femme Footwear Court Ca...,1921.88,20.0,817.88,80,9600.00,4416.00,4.995109
669,PROD-158664,PROD-174349 SEG-517028 Femme Footwear Trailbla...,1516.89,13.0,475.85,43,7310.00,3443.44,4.819071
141,PROD-123475,PROD-171460 SEG-516505 Junior Apparel Cozy Tro...,318.91,10.0,91.34,34,1519.94,773.30,4.766047
2096,PROD-181294,PROD-189301 SEG-520492 Femme Footwear Trailbla...,1767.00,10.0,805.60,44,8360.00,4230.16,4.731183
1034,PROD-165575,PROD-109663 SEG-502021 Femme Footwear Court Ca...,1931.91,19.0,883.11,76,9120.00,4195.20,4.720717
734,PROD-159660,PROD-168013 SEG-515888 Junior Apparel Cozy Pul...,336.36,14.0,81.56,33,1580.95,600.60,4.700172
2100,PROD-181300,PROD-189280 SEG-520490 Femme Footwear Trailbla...,1710.00,11.0,652.46,41,7790.00,3941.74,4.555556

In [44]:
#Stock-out Risk Analysis
stockout_risk = product_sales_inventory[
    (product_sales_inventory["Units_Sold"] > 0) &
    (product_sales_inventory["Current_Inventory_Units"] <= 0)
].copy()

stockout_risk = stockout_risk.sort_values(
    "Units_Sold",
    ascending=False
)

stockout_risk.head(20)
print("Potential stock-out products:", len(stockout_risk))

print(
    "Net Sales at stock-out risk:",
    round(stockout_risk["Net_Sales"].sum(), 2)
)

print(
    "Units Sold from stock-out risk products:",
    stockout_risk["Units_Sold"].sum()
)

Potential stock-out products: 3
Net Sales at stock-out risk: 7002.24
Units Sold from stock-out risk products: 112.0

In [45]:
#Inventory Coverage
sales_months = 11

product_sales_inventory["Avg_Monthly_Units_Sold"] = (
    product_sales_inventory["Units_Sold"] / sales_months
)
product_sales_inventory["Inventory_Coverage_Months"] = np.where(
    product_sales_inventory["Avg_Monthly_Units_Sold"] > 0,
    product_sales_inventory["Current_Inventory_Units"] /
    product_sales_inventory["Avg_Monthly_Units_Sold"],
    np.nan
)
high_inventory_coverage = (
    product_sales_inventory[
        product_sales_inventory["Current_Inventory_Units"] > 0
    ]
    .sort_values(
        "Inventory_Coverage_Months",
        ascending=False
    )
)

high_inventory_coverage.head(20)

,Product No,Product Description,Net_Sales,Units_Sold,Profit,Current_Inventory_Units,Current_Inventory_Value,Current_Inventory_Cost,Inventory_to_Sales_Ratio,Avg_Monthly_Units_Sold,Inventory_Coverage_Months
1257,PROD-168499,PROD-187243 SEG-520058 Femme Footwear Boot Col...,1500.00,10.0,842.00,69,9660.00,4540.18,6.440000,0.909091,75.900000
520,PROD-152708,PROD-166588 SEG-515644 Femme Footwear Trailbla...,1729.97,10.0,779.07,58,11499.99,5515.34,6.647508,0.909091,63.800000
1867,PROD-175940,PROD-153425 SEG-512517 Femme Footwear Court Ca...,1670.50,13.0,815.36,71,9230.00,4670.38,5.525292,1.181818,60.076923
2260,PROD-190416,PROD-137181 SEG-508412 Junior Apparel Crew Tee...,320.00,8.0,224.00,43,1720.00,516.00,5.375000,0.727273,59.125000
1035,PROD-165576,PROD-109664 SEG-502021 Femme Footwear Court Ca...,1684.94,16.0,801.74,80,9600.00,4416.00,5.697532,1.454545,55.000000
1982,PROD-178806,PROD-141517 SEG-509388 Scholar Footwear Hardco...,3135.75,18.0,1450.77,90,16650.00,8424.90,5.309735,1.636364,55.000000
1037,PROD-165578,PROD-109666 SEG-502021 Femme Footwear Court Ca...,1544.44,16.0,661.24,78,9360.00,4305.60,6.060449,1.454545,53.625000
403,PROD-149692,PROD-103117 SEG-500427 Scholar Footwear Court ...,3009.92,40.0,1518.96,189,15120.00,7048.65,5.023389,3.636364,51.975000
1894,PROD-175997,PROD-166631 SEG-515650 Femme Footwear Trailbla...,1765.25,14.0,808.91,66,8910.00,4508.46,5.047444,1.272727,51.857143
2096,PROD-181294,PROD-189301 SEG-520492 Femme Footwear Trailbla...,1767.00,10.0,805.60,44,8360.00,4230.16,4.731183,0.909091,48.400000
2116,PROD-181833,PROD-152143 SEG-512250 Scholar Footwear Flight...,3076.00,32.0,1456.80,137,13700.00,6932.20,4.453836,2.909091,47.093750
522,PROD-152711,PROD-166591 SEG-515644 Femme Footwear Trailbla...,2198.88,16.0,677.43,68,13399.98,6466.19,6.094002,1.454545,46.750000
2124,PROD-181867,PROD-152573 SEG-512317 Scholar Footwear Court ...,2985.40,33.0,1479.29,139,12788.00,6361.74,4.283513,3.000000,46.333333
2111,PROD-181817,PROD-152122 SEG-512249 Scholar Footwear Flight...,2994.93,32.0,1375.73,133,13300.00,6729.80,4.440838,2.909091,45.718750
1034,PROD-165575,PROD-109663 SEG-502021 Femme Footwear Court Ca...,1931.91,19.0,883.11,76,9120.00,4195.20,4.720717,1.727273,44.000000
1036,PROD-165577,PROD-109665 SEG-502021 Femme Footwear Court Ca...,1921.88,20.0,817.88,80,9600.00,4416.00,4.995109,1.818182,44.000000
2099,PROD-181298,PROD-189278 SEG-520490 Femme Footwear Trailbla...,1681.50,10.0,720.10,40,7600.00,3845.60,4.519774,0.909091,44.000000
1749,PROD-173379,PROD-108108 SEG-501609 Junior Apparel Denim Cl...,315.43,10.0,120.43,40,1800.00,780.00,5.706496,0.909091,44.000000
1872,PROD-175945,PROD-153421 SEG-512517 Femme Footwear Court Ca...,2151.50,17.0,1033.24,67,8710.00,4407.26,4.048338,1.545455,43.352941
1884,PROD-175964,PROD-154303 SEG-512708 Femme Footwear Trailbla...,1717.00,11.0,770.78,43,7310.00,3698.86,4.257426,1.000000,43.000000

In [49]:
#Risk Classification
def classify_inventory_risk(row):
    if row["Current_Inventory_Units"] <= 0 and row["Units_Sold"] > 0:
        return "Stock-out Risk"
    elif row["Inventory_Coverage_Months"] >= 6:
        return "Potential Overstock"
    elif row["Inventory_Coverage_Months"] <= 1:
        return "Low Stock"
    else:
        return "Healthy"

product_sales_inventory["Inventory_Risk"] = (
    product_sales_inventory.apply(
        classify_inventory_risk,
        axis=1
    )
)

In [50]:
risk_summary = (
    product_sales_inventory["Inventory_Risk"]
    .value_counts()
    .reset_index()
)

risk_summary.columns = ["Inventory Risk", "Product Count"]

risk_summary

product_sales_inventory[
    [
        "Product No",
        "Product Description",
        "Net_Sales",
        "Units_Sold",
        "Current_Inventory_Units",
        "Current_Inventory_Value",
        "Inventory_Coverage_Months",
        "Inventory_Risk"
    ]
].head(20)

,Product No,Product Description,Net_Sales,Units_Sold,Current_Inventory_Units,Current_Inventory_Value,Inventory_Coverage_Months,Inventory_Risk
0,PROD-100043,PROD-189472 SEG-520541 Femme Footwear Boot Col...,2432.00,16.0,30,4800.0,20.625000,Potential Overstock
1,PROD-100044,PROD-189473 SEG-520541 Femme Footwear Boot Col...,3792.00,24.0,29,4640.0,13.291667,Potential Overstock
2,PROD-100045,PROD-189474 SEG-520541 Femme Footwear Boot Col...,2104.00,14.0,22,3520.0,17.285714,Potential Overstock
3,PROD-100051,PROD-189481 SEG-520542 Femme Footwear Boot Col...,1600.00,10.0,11,1760.0,12.100000,Potential Overstock
4,PROD-100052,PROD-189475 SEG-520542 Femme Footwear Boot Col...,1760.00,11.0,28,4480.0,28.000000,Potential Overstock
5,PROD-100353,PROD-164489 SEG-515310 Femme Footwear Court Ca...,5135.38,66.0,42,5040.0,7.000000,Potential Overstock
6,PROD-100354,PROD-164490 SEG-515310 Femme Footwear Court Ca...,6962.18,89.0,44,5280.0,5.438202,Healthy
7,PROD-100355,PROD-164491 SEG-515310 Femme Footwear Court Ca...,8671.02,110.0,65,7800.0,6.500000,Potential Overstock
8,PROD-100356,PROD-164492 SEG-515310 Femme Footwear Court Ca...,14499.23,188.0,65,7800.0,3.803191,Healthy
9,PROD-100357,PROD-164493 SEG-515310 Femme Footwear Court Ca...,16307.04,213.0,73,8760.0,3.769953,Healthy
10,PROD-100358,PROD-164494 SEG-515310 Femme Footwear Court Ca...,20189.52,263.0,41,4920.0,1.714829,Healthy
11,PROD-100359,PROD-164495 SEG-515310 Femme Footwear Court Ca...,9987.70,132.0,13,1560.0,1.083333,Healthy
12,PROD-100360,PROD-164482 SEG-515310 Femme Footwear Court Ca...,4679.91,59.0,0,0.0,0.000000,Stock-out Risk
13,PROD-100362,PROD-164484 SEG-515310 Femme Footwear Court Ca...,3963.20,51.0,46,5520.0,9.921569,Potential Overstock
14,PROD-100364,PROD-164488 SEG-515310 Femme Footwear Court Ca...,2983.65,38.0,46,5520.0,13.315789,Potential Overstock
15,PROD-100433,PROD-164663 SEG-515333 Scholar Footwear Court ...,16340.06,218.0,39,3588.0,1.967890,Healthy
16,PROD-100434,PROD-164662 SEG-515333 Scholar Footwear Court ...,16077.67,216.0,66,6072.0,3.361111,Healthy
17,PROD-100435,PROD-164665 SEG-515333 Scholar Footwear Court ...,20149.55,271.0,42,3864.0,1.704797,Healthy
18,PROD-100436,PROD-164664 SEG-515333 Scholar Footwear Court ...,21350.04,292.0,63,5796.0,2.373288,Healthy
19,PROD-100437,PROD-164667 SEG-515333 Scholar Footwear Court ...,26126.25,354.0,93,8556.0,2.889831,Healthy

In [51]:
product_sales_inventory["Inventory_Risk"].value_counts()

Inventory_Risk
Potential Overstock    1461
Healthy                 824
Low Stock                38
Stock-out Risk            3
Name: count, dtype: int64

In [52]:
stockout_risk = product_sales_inventory[
    (product_sales_inventory["Units_Sold"] > 0) &
    (product_sales_inventory["Current_Inventory_Units"] <= 0)
].copy()

stockout_risk[
    [
        "Product No",
        "Product Description",
        "Net_Sales",
        "Units_Sold",
        "Profit",
        "Current_Inventory_Units",
        "Current_Inventory_Value",
        "Inventory_Risk"
    ]
]

,Product No,Product Description,Net_Sales,Units_Sold,Profit,Current_Inventory_Units,Current_Inventory_Value,Inventory_Risk
12,PROD-100360,PROD-164482 SEG-515310 Femme Footwear Court Ca...,4679.91,59.0,1187.68,0,0.00,Stock-out Risk
148,PROD-123509,PROD-171497 SEG-516514 Junior Apparel Crop Pan...,822.43,34.0,274.46,-2,-110.02,Stock-out Risk
979,PROD-163861,PROD-180137 SEG-518154 Femme Footwear Trailbla...,1499.90,19.0,552.50,-1,-100.00,Stock-out Risk

In [53]:
risk_summary = (
    product_sales_inventory
    .groupby("Inventory_Risk")
    .agg(
        Product_Count=("Product No", "count"),
        Net_Sales=("Net_Sales", "sum"),
        Units_Sold=("Units_Sold", "sum"),
        Inventory_Value=("Current_Inventory_Value", "sum")
    )
    .reset_index()
    .sort_values("Product_Count", ascending=False)
)

risk_summary

risk_summary.to_csv(
    "../data/inventory_risk_summary.csv",
    index=False
)